[package]
name = "xavier-robot"
version = "0.1.0"
edition = "2021"

[dependencies]
approx = "0.5.1"
apriltag = "0.4.0"
assert_approx_eq = "1.1.0"

[dependencies.nokhwa]
version = "0.10.0"
# Use the native input backends, enable WGPU integration
features = ["input-native", "output-threaded"]
